# Generated by Django 2.2 on 2021-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliese_api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='item_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
